# Generated by Django 4.2.6 on 2023-10-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_slug',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
