# Generated by Django 4.2.6 on 2023-10-15 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='un_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.unit', verbose_name='Unit'),
        ),
    ]
