# Generated by Django 4.2.6 on 2023-10-13 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
                ('c_body', models.TextField(verbose_name='body')),
                ('c_id_read_by_admin', models.BooleanField(db_index=True, default=False, verbose_name='read by admin')),
                ('c_response_admin', models.CharField(blank=True, max_length=200, null=True, verbose_name='admin response')),
                ('c_datetime', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('c_update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_title', models.CharField(db_index=True, max_length=200, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.CreateModel(
            name='RatingStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_datetime', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('rs_update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('r_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feedback.rating', verbose_name='rating id')),
            ],
            options={
                'verbose_name': 'Stores Rating',
                'verbose_name_plural': 'Stores Ratings',
            },
        ),
    ]
