# Generated by Django 4.2.6 on 2023-10-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_sales', '0001_initial'),
        ('invoice_customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentity',
            name='isi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice_sales.invoicesales', verbose_name='Invoice Sales'),
        ),
        migrations.AddField(
            model_name='productentity',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='product'),
        ),
    ]
