# Generated by Django 4.2.6 on 2023-10-14 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('invoice_customer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentity',
            name='u_store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storeProductEntity', to=settings.AUTH_USER_MODEL, verbose_name='store'),
        ),
        migrations.AddField(
            model_name='invoicecustomeritem',
            name='ic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_customer.invoicecustomer', verbose_name='Invoice'),
        ),
        migrations.AddField(
            model_name='invoicecustomeritem',
            name='p_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='invoicecustomeritem',
            name='pe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice_customer.productentity', verbose_name='Product Price'),
        ),
        migrations.AddField(
            model_name='invoicecustomer',
            name='u_customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customerInvoiceCustomer', to=settings.AUTH_USER_MODEL, verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='invoicecustomer',
            name='u_store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storeCustomer', to='user.store', verbose_name='store'),
        ),
    ]
