# Generated by Django 4.2.6 on 2023-10-10 17:44

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.MyUserManager()),
            ],
        ),
    ]
