# Generated by Django 4.2.6 on 2023-10-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_code_meli',
            field=models.CharField(db_index=True, max_length=10, verbose_name='code meli'),
        ),
    ]
