# Generated by Django 4.2.6 on 2023-10-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='up_id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.userprofile', verbose_name='user profile id'),
        ),
    ]
