# Generated by Django 4.2.6 on 2023-10-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_up_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ut_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.usertype', verbose_name='user type id'),
        ),
    ]
