# Generated by Django 4.2.6 on 2023-10-11 05:02

from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_ut_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_code_meli',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='code meli'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_phone_number',
            field=models.CharField(db_index=True, max_length=200, unique=True, validators=[user.validators.check_phone], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='up_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.userprofile', verbose_name='user profile id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ut_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.usertype', verbose_name='user type id'),
        ),
    ]
