# Generated by Django 4.2.6 on 2023-10-11 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
    ]
