# Generated by Django 4.2.6 on 2023-10-15 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('invoice_sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicesales',
            name='u_store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storeSales', to='user.store', verbose_name='store'),
        ),
    ]
